package zhh.ap.bean;

public class AppointmentRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.opt_time
     *
     * @mbggenerated
     */
    private String optTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.appoint_time
     *
     * @mbggenerated
     */
    private String appointTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.doctor_id
     *
     * @mbggenerated
     */
    private String doctorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.doctor_name
     *
     * @mbggenerated
     */
    private String doctorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.hospital
     *
     * @mbggenerated
     */
    private String hospital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.department
     *
     * @mbggenerated
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.disease
     *
     * @mbggenerated
     */
    private String disease;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.finish_time
     *
     * @mbggenerated
     */
    private String finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.error
     *
     * @mbggenerated
     */
    private String error;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.id
     *
     * @return the value of app_appointment_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.id
     *
     * @param id the value for app_appointment_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.user_id
     *
     * @return the value of app_appointment_record.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.user_id
     *
     * @param userId the value for app_appointment_record.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.user_name
     *
     * @return the value of app_appointment_record.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.user_name
     *
     * @param userName the value for app_appointment_record.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.opt_time
     *
     * @return the value of app_appointment_record.opt_time
     *
     * @mbggenerated
     */
    public String getOptTime() {
        return optTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.opt_time
     *
     * @param optTime the value for app_appointment_record.opt_time
     *
     * @mbggenerated
     */
    public void setOptTime(String optTime) {
        this.optTime = optTime == null ? null : optTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.appoint_time
     *
     * @return the value of app_appointment_record.appoint_time
     *
     * @mbggenerated
     */
    public String getAppointTime() {
        return appointTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.appoint_time
     *
     * @param appointTime the value for app_appointment_record.appoint_time
     *
     * @mbggenerated
     */
    public void setAppointTime(String appointTime) {
        this.appointTime = appointTime == null ? null : appointTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.doctor_id
     *
     * @return the value of app_appointment_record.doctor_id
     *
     * @mbggenerated
     */
    public String getDoctorId() {
        return doctorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.doctor_id
     *
     * @param doctorId the value for app_appointment_record.doctor_id
     *
     * @mbggenerated
     */
    public void setDoctorId(String doctorId) {
        this.doctorId = doctorId == null ? null : doctorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.doctor_name
     *
     * @return the value of app_appointment_record.doctor_name
     *
     * @mbggenerated
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.doctor_name
     *
     * @param doctorName the value for app_appointment_record.doctor_name
     *
     * @mbggenerated
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName == null ? null : doctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.hospital
     *
     * @return the value of app_appointment_record.hospital
     *
     * @mbggenerated
     */
    public String getHospital() {
        return hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.hospital
     *
     * @param hospital the value for app_appointment_record.hospital
     *
     * @mbggenerated
     */
    public void setHospital(String hospital) {
        this.hospital = hospital == null ? null : hospital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.department
     *
     * @return the value of app_appointment_record.department
     *
     * @mbggenerated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.department
     *
     * @param department the value for app_appointment_record.department
     *
     * @mbggenerated
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.disease
     *
     * @return the value of app_appointment_record.disease
     *
     * @mbggenerated
     */
    public String getDisease() {
        return disease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.disease
     *
     * @param disease the value for app_appointment_record.disease
     *
     * @mbggenerated
     */
    public void setDisease(String disease) {
        this.disease = disease == null ? null : disease.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.finish_time
     *
     * @return the value of app_appointment_record.finish_time
     *
     * @mbggenerated
     */
    public String getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.finish_time
     *
     * @param finishTime the value for app_appointment_record.finish_time
     *
     * @mbggenerated
     */
    public void setFinishTime(String finishTime) {
        this.finishTime = finishTime == null ? null : finishTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.error
     *
     * @return the value of app_appointment_record.error
     *
     * @mbggenerated
     */
    public String getError() {
        return error;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.error
     *
     * @param error the value for app_appointment_record.error
     *
     * @mbggenerated
     */
    public void setError(String error) {
        this.error = error == null ? null : error.trim();
    }
}