package zhh.ap.bean;

public class AppointmentRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.user_code
     *
     * @mbggenerated
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.opt_time
     *
     * @mbggenerated
     */
    private String optTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.appoint_time
     *
     * @mbggenerated
     */
    private String appointTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.doctor_code
     *
     * @mbggenerated
     */
    private String doctorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.doctor_name
     *
     * @mbggenerated
     */
    private String doctorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.hospital
     *
     * @mbggenerated
     */
    private String hospital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.department
     *
     * @mbggenerated
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.disease
     *
     * @mbggenerated
     */
    private String disease;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.finish_time
     *
     * @mbggenerated
     */
    private String finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.fail_reason
     *
     * @mbggenerated
     */
    private String failReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.hospital_code
     *
     * @mbggenerated
     */
    private String hospitalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.hospital_name
     *
     * @mbggenerated
     */
    private String hospitalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.department_code
     *
     * @mbggenerated
     */
    private String departmentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_appointment_record.department_name
     *
     * @mbggenerated
     */
    private String departmentName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.id
     *
     * @return the value of app_appointment_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.id
     *
     * @param id the value for app_appointment_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.user_code
     *
     * @return the value of app_appointment_record.user_code
     *
     * @mbggenerated
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.user_code
     *
     * @param userCode the value for app_appointment_record.user_code
     *
     * @mbggenerated
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.user_name
     *
     * @return the value of app_appointment_record.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.user_name
     *
     * @param userName the value for app_appointment_record.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.opt_time
     *
     * @return the value of app_appointment_record.opt_time
     *
     * @mbggenerated
     */
    public String getOptTime() {
        return optTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.opt_time
     *
     * @param optTime the value for app_appointment_record.opt_time
     *
     * @mbggenerated
     */
    public void setOptTime(String optTime) {
        this.optTime = optTime == null ? null : optTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.appoint_time
     *
     * @return the value of app_appointment_record.appoint_time
     *
     * @mbggenerated
     */
    public String getAppointTime() {
        return appointTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.appoint_time
     *
     * @param appointTime the value for app_appointment_record.appoint_time
     *
     * @mbggenerated
     */
    public void setAppointTime(String appointTime) {
        this.appointTime = appointTime == null ? null : appointTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.doctor_code
     *
     * @return the value of app_appointment_record.doctor_code
     *
     * @mbggenerated
     */
    public String getDoctorCode() {
        return doctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.doctor_code
     *
     * @param doctorCode the value for app_appointment_record.doctor_code
     *
     * @mbggenerated
     */
    public void setDoctorCode(String doctorCode) {
        this.doctorCode = doctorCode == null ? null : doctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.doctor_name
     *
     * @return the value of app_appointment_record.doctor_name
     *
     * @mbggenerated
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.doctor_name
     *
     * @param doctorName the value for app_appointment_record.doctor_name
     *
     * @mbggenerated
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName == null ? null : doctorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.hospital
     *
     * @return the value of app_appointment_record.hospital
     *
     * @mbggenerated
     */
    public String getHospital() {
        return hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.hospital
     *
     * @param hospital the value for app_appointment_record.hospital
     *
     * @mbggenerated
     */
    public void setHospital(String hospital) {
        this.hospital = hospital == null ? null : hospital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.department
     *
     * @return the value of app_appointment_record.department
     *
     * @mbggenerated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.department
     *
     * @param department the value for app_appointment_record.department
     *
     * @mbggenerated
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.disease
     *
     * @return the value of app_appointment_record.disease
     *
     * @mbggenerated
     */
    public String getDisease() {
        return disease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.disease
     *
     * @param disease the value for app_appointment_record.disease
     *
     * @mbggenerated
     */
    public void setDisease(String disease) {
        this.disease = disease == null ? null : disease.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.finish_time
     *
     * @return the value of app_appointment_record.finish_time
     *
     * @mbggenerated
     */
    public String getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.finish_time
     *
     * @param finishTime the value for app_appointment_record.finish_time
     *
     * @mbggenerated
     */
    public void setFinishTime(String finishTime) {
        this.finishTime = finishTime == null ? null : finishTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.fail_reason
     *
     * @return the value of app_appointment_record.fail_reason
     *
     * @mbggenerated
     */
    public String getFailReason() {
        return failReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.fail_reason
     *
     * @param failReason the value for app_appointment_record.fail_reason
     *
     * @mbggenerated
     */
    public void setFailReason(String failReason) {
        this.failReason = failReason == null ? null : failReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.hospital_code
     *
     * @return the value of app_appointment_record.hospital_code
     *
     * @mbggenerated
     */
    public String getHospitalCode() {
        return hospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.hospital_code
     *
     * @param hospitalCode the value for app_appointment_record.hospital_code
     *
     * @mbggenerated
     */
    public void setHospitalCode(String hospitalCode) {
        this.hospitalCode = hospitalCode == null ? null : hospitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.hospital_name
     *
     * @return the value of app_appointment_record.hospital_name
     *
     * @mbggenerated
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.hospital_name
     *
     * @param hospitalName the value for app_appointment_record.hospital_name
     *
     * @mbggenerated
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName == null ? null : hospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.department_code
     *
     * @return the value of app_appointment_record.department_code
     *
     * @mbggenerated
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.department_code
     *
     * @param departmentCode the value for app_appointment_record.department_code
     *
     * @mbggenerated
     */
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode == null ? null : departmentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_appointment_record.department_name
     *
     * @return the value of app_appointment_record.department_name
     *
     * @mbggenerated
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_appointment_record.department_name
     *
     * @param departmentName the value for app_appointment_record.department_name
     *
     * @mbggenerated
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    @Override
    public String toString() {
        return "AppointmentRecord{" +
                "id=" + id +
                ", userCode='" + userCode + '\'' +
                ", userName='" + userName + '\'' +
                ", optTime='" + optTime + '\'' +
                ", appointTime='" + appointTime + '\'' +
                ", doctorCode='" + doctorCode + '\'' +
                ", doctorName='" + doctorName + '\'' +
                ", hospital='" + hospital + '\'' +
                ", department='" + department + '\'' +
                ", disease='" + disease + '\'' +
                ", finishTime='" + finishTime + '\'' +
                ", failReason='" + failReason + '\'' +
                ", hospitalCode='" + hospitalCode + '\'' +
                ", hospitalName='" + hospitalName + '\'' +
                ", departmentCode='" + departmentCode + '\'' +
                ", departmentName='" + departmentName + '\'' +
                '}';
    }
}