package zhh.ap.bean;

public class DepartHospitalRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_department_hospital.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_department_hospital.department_code
     *
     * @mbggenerated
     */
    private String departmentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_department_hospital.hospital_code
     *
     * @mbggenerated
     */
    private String hospitalCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_department_hospital.id
     *
     * @return the value of app_department_hospital.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_department_hospital.id
     *
     * @param id the value for app_department_hospital.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_department_hospital.department_code
     *
     * @return the value of app_department_hospital.department_code
     *
     * @mbggenerated
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_department_hospital.department_code
     *
     * @param departmentCode the value for app_department_hospital.department_code
     *
     * @mbggenerated
     */
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode == null ? null : departmentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_department_hospital.hospital_code
     *
     * @return the value of app_department_hospital.hospital_code
     *
     * @mbggenerated
     */
    public String getHospitalCode() {
        return hospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_department_hospital.hospital_code
     *
     * @param hospitalCode the value for app_department_hospital.hospital_code
     *
     * @mbggenerated
     */
    public void setHospitalCode(String hospitalCode) {
        this.hospitalCode = hospitalCode == null ? null : hospitalCode.trim();
    }
}