package zhh.ap.bean;

public class Doctor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_doctor.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_doctor.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_doctor.age
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_doctor.level
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_doctor.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_doctor.exprience
     *
     * @mbggenerated
     */
    private String exprience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_doctor.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_doctor.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_doctor.phone_number
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_doctor.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_doctor.hospital_code
     *
     * @mbggenerated
     */
    private String hospitalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_doctor.doctor_code
     *
     * @mbggenerated
     */
    private String doctorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_doctor.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_doctor.IDcard
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_doctor.department_code
     *
     * @mbggenerated
     */
    private String departmentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_doctor.hospitalName
     *
     * @mbggenerated
     */
    private String hospitalname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_doctor.departmentName
     *
     * @mbggenerated
     */
    private String departmentname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_doctor.id
     *
     * @return the value of app_doctor.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_doctor.id
     *
     * @param id the value for app_doctor.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_doctor.name
     *
     * @return the value of app_doctor.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_doctor.name
     *
     * @param name the value for app_doctor.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_doctor.age
     *
     * @return the value of app_doctor.age
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_doctor.age
     *
     * @param age the value for app_doctor.age
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_doctor.level
     *
     * @return the value of app_doctor.level
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_doctor.level
     *
     * @param level the value for app_doctor.level
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_doctor.sex
     *
     * @return the value of app_doctor.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_doctor.sex
     *
     * @param sex the value for app_doctor.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_doctor.exprience
     *
     * @return the value of app_doctor.exprience
     *
     * @mbggenerated
     */
    public String getExprience() {
        return exprience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_doctor.exprience
     *
     * @param exprience the value for app_doctor.exprience
     *
     * @mbggenerated
     */
    public void setExprience(String exprience) {
        this.exprience = exprience == null ? null : exprience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_doctor.image
     *
     * @return the value of app_doctor.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_doctor.image
     *
     * @param image the value for app_doctor.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_doctor.email
     *
     * @return the value of app_doctor.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_doctor.email
     *
     * @param email the value for app_doctor.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_doctor.phone_number
     *
     * @return the value of app_doctor.phone_number
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_doctor.phone_number
     *
     * @param phoneNumber the value for app_doctor.phone_number
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_doctor.address
     *
     * @return the value of app_doctor.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_doctor.address
     *
     * @param address the value for app_doctor.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_doctor.hospital_code
     *
     * @return the value of app_doctor.hospital_code
     *
     * @mbggenerated
     */
    public String getHospitalCode() {
        return hospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_doctor.hospital_code
     *
     * @param hospitalCode the value for app_doctor.hospital_code
     *
     * @mbggenerated
     */
    public void setHospitalCode(String hospitalCode) {
        this.hospitalCode = hospitalCode == null ? null : hospitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_doctor.doctor_code
     *
     * @return the value of app_doctor.doctor_code
     *
     * @mbggenerated
     */
    public String getDoctorCode() {
        return doctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_doctor.doctor_code
     *
     * @param doctorCode the value for app_doctor.doctor_code
     *
     * @mbggenerated
     */
    public void setDoctorCode(String doctorCode) {
        this.doctorCode = doctorCode == null ? null : doctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_doctor.password
     *
     * @return the value of app_doctor.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_doctor.password
     *
     * @param password the value for app_doctor.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_doctor.IDcard
     *
     * @return the value of app_doctor.IDcard
     *
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_doctor.IDcard
     *
     * @param idcard the value for app_doctor.IDcard
     *
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_doctor.department_code
     *
     * @return the value of app_doctor.department_code
     *
     * @mbggenerated
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_doctor.department_code
     *
     * @param departmentCode the value for app_doctor.department_code
     *
     * @mbggenerated
     */
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode == null ? null : departmentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_doctor.hospitalName
     *
     * @return the value of app_doctor.hospitalName
     *
     * @mbggenerated
     */
    public String getHospitalname() {
        return hospitalname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_doctor.hospitalName
     *
     * @param hospitalname the value for app_doctor.hospitalName
     *
     * @mbggenerated
     */
    public void setHospitalname(String hospitalname) {
        this.hospitalname = hospitalname == null ? null : hospitalname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_doctor.departmentName
     *
     * @return the value of app_doctor.departmentName
     *
     * @mbggenerated
     */
    public String getDepartmentname() {
        return departmentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_doctor.departmentName
     *
     * @param departmentname the value for app_doctor.departmentName
     *
     * @mbggenerated
     */
    public void setDepartmentname(String departmentname) {
        this.departmentname = departmentname == null ? null : departmentname.trim();
    }

    @Override
    public String toString() {
        return "Doctor{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", age=" + age +
                ", level='" + level + '\'' +
                ", sex='" + sex + '\'' +
                ", exprience='" + exprience + '\'' +
                ", image='" + image + '\'' +
                ", email='" + email + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", address='" + address + '\'' +
                ", hospitalCode='" + hospitalCode + '\'' +
                ", doctorCode='" + doctorCode + '\'' +
                ", password='" + password + '\'' +
                ", idcard='" + idcard + '\'' +
                ", departmentCode='" + departmentCode + '\'' +
                ", hospitalname='" + hospitalname + '\'' +
                ", departmentname='" + departmentname + '\'' +
                '}';
    }
}