package zhh.ap.bean;

public class Schedule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_schedule.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_schedule.department_code
     *
     * @mbggenerated
     */
    private String departmentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_schedule.hospital_code
     *
     * @mbggenerated
     */
    private String hospitalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_schedule.appoint_day
     *
     * @mbggenerated
     */
    private String appointDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_schedule.doctor_code
     *
     * @mbggenerated
     */
    private String doctorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_schedule.total_limit
     *
     * @mbggenerated
     */
    private Integer totalLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_schedule.left_limit
     *
     * @mbggenerated
     */
    private Integer leftLimit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_schedule.id
     *
     * @return the value of app_schedule.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_schedule.id
     *
     * @param id the value for app_schedule.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_schedule.department_code
     *
     * @return the value of app_schedule.department_code
     *
     * @mbggenerated
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_schedule.department_code
     *
     * @param departmentCode the value for app_schedule.department_code
     *
     * @mbggenerated
     */
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode == null ? null : departmentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_schedule.hospital_code
     *
     * @return the value of app_schedule.hospital_code
     *
     * @mbggenerated
     */
    public String getHospitalCode() {
        return hospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_schedule.hospital_code
     *
     * @param hospitalCode the value for app_schedule.hospital_code
     *
     * @mbggenerated
     */
    public void setHospitalCode(String hospitalCode) {
        this.hospitalCode = hospitalCode == null ? null : hospitalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_schedule.appoint_day
     *
     * @return the value of app_schedule.appoint_day
     *
     * @mbggenerated
     */
    public String getAppointDay() {
        return appointDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_schedule.appoint_day
     *
     * @param appointDay the value for app_schedule.appoint_day
     *
     * @mbggenerated
     */
    public void setAppointDay(String appointDay) {
        this.appointDay = appointDay == null ? null : appointDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_schedule.doctor_code
     *
     * @return the value of app_schedule.doctor_code
     *
     * @mbggenerated
     */
    public String getDoctorCode() {
        return doctorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_schedule.doctor_code
     *
     * @param doctorCode the value for app_schedule.doctor_code
     *
     * @mbggenerated
     */
    public void setDoctorCode(String doctorCode) {
        this.doctorCode = doctorCode == null ? null : doctorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_schedule.total_limit
     *
     * @return the value of app_schedule.total_limit
     *
     * @mbggenerated
     */
    public Integer getTotalLimit() {
        return totalLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_schedule.total_limit
     *
     * @param totalLimit the value for app_schedule.total_limit
     *
     * @mbggenerated
     */
    public void setTotalLimit(Integer totalLimit) {
        this.totalLimit = totalLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_schedule.left_limit
     *
     * @return the value of app_schedule.left_limit
     *
     * @mbggenerated
     */
    public Integer getLeftLimit() {
        return leftLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_schedule.left_limit
     *
     * @param leftLimit the value for app_schedule.left_limit
     *
     * @mbggenerated
     */
    public void setLeftLimit(Integer leftLimit) {
        this.leftLimit = leftLimit;
    }
}