package zhh.ap.bean;

public class StaticDataArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_h_area.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_h_area.parent
     *
     * @mbggenerated
     */
    private Integer parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_h_area.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_h_area.zipcode
     *
     * @mbggenerated
     */
    private Integer zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sd_h_area.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_h_area.id
     *
     * @return the value of sd_h_area.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_h_area.id
     *
     * @param id the value for sd_h_area.id
     *
     * @mbggenerated
     */
    private void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_h_area.parent
     *
     * @return the value of sd_h_area.parent
     *
     * @mbggenerated
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_h_area.parent
     *
     * @param parent the value for sd_h_area.parent
     *
     * @mbggenerated
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_h_area.name
     *
     * @return the value of sd_h_area.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_h_area.name
     *
     * @param name the value for sd_h_area.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_h_area.zipcode
     *
     * @return the value of sd_h_area.zipcode
     *
     * @mbggenerated
     */
    public Integer getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_h_area.zipcode
     *
     * @param zipcode the value for sd_h_area.zipcode
     *
     * @mbggenerated
     */
    public void setZipcode(Integer zipcode) {
        this.zipcode = zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sd_h_area.code
     *
     * @return the value of sd_h_area.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sd_h_area.code
     *
     * @param code the value for sd_h_area.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}