package zhh.ap.dao;

import java.util.List;
import zhh.ap.bean.AppointmentRecord;

public interface AppointmentRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_appointment_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_appointment_record
     *
     * @mbggenerated
     */
    int insert(AppointmentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_appointment_record
     *
     * @mbggenerated
     */
    AppointmentRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_appointment_record
     *
     * @mbggenerated
     */
    List<AppointmentRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_appointment_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppointmentRecord record);

    List<AppointmentRecord> selectByUsercode(String userCode);

    List<AppointmentRecord> selectByDoctorcode(String doctorCode);

    AppointmentRecord selectByColumn(String columnName, String value);

    AppointmentRecord selectByUserAndTime(String userCode, String appointTime);
}