package zhh.ap.dao;

import java.util.List;
import zhh.ap.bean.Doctor;

public interface DoctorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_doctor
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_doctor
     *
     * @mbggenerated
     */
    int insert(Doctor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_doctor
     *
     * @mbggenerated
     */
    Doctor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_doctor
     *
     * @mbggenerated
     */
    List<Doctor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_doctor
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Doctor record);

    Doctor selectByPhoneNumberAndEmail(String phoneNumber, String email);

    Doctor selectByIdCard(String idCard);

    Doctor selectByPhoneNumber(String phoneNumber);

    Doctor selectByColumn(String columnName, String value);
}