package zhh.ap.dao;

import java.util.List;
import zhh.ap.bean.Evaluation;

public interface EvaluationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_evaluation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_evaluation
     *
     * @mbggenerated
     */
    int insert(Evaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_evaluation
     *
     * @mbggenerated
     */
    Evaluation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_evaluation
     *
     * @mbggenerated
     */
    List<Evaluation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_evaluation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Evaluation record);
}