package zhh.ap.dao;

import java.util.List;
import zhh.ap.bean.Hospital;

public interface HospitalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_hospital
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_hospital
     *
     * @mbggenerated
     */
    int insert(Hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_hospital
     *
     * @mbggenerated
     */
    Hospital selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_hospital
     *
     * @mbggenerated
     */
    List<Hospital> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_hospital
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Hospital record);

    List<Hospital> selectByArea(String area);

    List<Hospital> selectByName(String area);

    List<Hospital> selectByLevel(String level);

    Hospital selectByCode(String code);
}