package zhh.ap.dao;

import java.util.List;
import zhh.ap.bean.Schedule;

public interface ScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_schedule
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_schedule
     *
     * @mbggenerated
     */
    int insert(Schedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_schedule
     *
     * @mbggenerated
     */
    Schedule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_schedule
     *
     * @mbggenerated
     */
    List<Schedule> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_schedule
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Schedule record);
}