package zhh.ap.dao;

import java.util.List;
import zhh.ap.bean.StaticDataType;

public interface StaticDataTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_h_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_h_type
     *
     * @mbggenerated
     */
    int insert(StaticDataType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_h_type
     *
     * @mbggenerated
     */
    StaticDataType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_h_type
     *
     * @mbggenerated
     */
    List<StaticDataType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_h_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StaticDataType record);
}