package zhh.ap.dao;

import java.util.List;
import zhh.ap.bean.StaticDataLevel;

public interface StaticDataLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_h_level
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_h_level
     *
     * @mbggenerated
     */
    int insert(StaticDataLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_h_level
     *
     * @mbggenerated
     */
    StaticDataLevel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_h_level
     *
     * @mbggenerated
     */
    List<StaticDataLevel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_h_level
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StaticDataLevel record);
}