package zhh.ap.dao;

import java.util.List;
import zhh.ap.bean.StaticDataArea;

public interface StaticDataAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_h_area
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_h_area
     *
     * @mbggenerated
     */
    int insert(StaticDataArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_h_area
     *
     * @mbggenerated
     */
    StaticDataArea selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_h_area
     *
     * @mbggenerated
     */
    List<StaticDataArea> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sd_h_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StaticDataArea record);
}