package zhh.ap.dao;

import java.util.List;

public interface HospitalBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_hospital
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_hospital
     *
     * @mbggenerated
     */
    int insert(HospitalBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_hospital
     *
     * @mbggenerated
     */
    HospitalBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_hospital
     *
     * @mbggenerated
     */
    List<HospitalBean> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_hospital
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HospitalBean record);
}